singleQuote: true
semi: false
printWidth: 100
trailingComma: none
plugins:
  - "@trivago/prettier-plugin-sort-imports"
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrder:
  - "^@/(.*)$"
  - "^./(.*)$"
